[package]
name = "simple_redis_1"
version = "0.1.0"
edition = "2024"

[[example]]
name = "hello-redis"
path = "examples/hello-redis.rs"


[dependencies]
tokio = { version = "1", features = ["full"] }
mini-redis = "0.4"
bytes = "1"
